apache:
   image: tutum/apache-php
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "80:80"
   links:
     - mariadb
   volumes:
     - ./app:/app

mariadb:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: wickbull
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: homestead
  ports:
    - "3306:3306"


phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
    - PMA_ARBITRARY=1
    - MYSQL_USER=wickbull
    - MYSQL_PASSWORD=root
    - MYSQL_ROOT_PASSWORD=root
  restart: always
  ports:
    - 8080:80
  volumes:
    - .sessions:/sessions

